name: Bug Report
description: Report a bug in Blitz
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the sections below.

  - type: input
    id: zig-version
    attributes:
      label: Zig Version
      description: Output of `zig version`
      placeholder: "0.15.0"
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      placeholder: "macOS 14.0 / Ubuntu 22.04 / Windows 11"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear description of what the bug is
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Minimal code or steps to reproduce the issue
      placeholder: |
        ```zig
        const blitz = @import("blitz");

        pub fn main() !void {
            try blitz.init();
            defer blitz.deinit();
            // ...
        }
        ```
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context (logs, screenshots, etc.)
